force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Have_Note__c.field-meta.xml
<CustomField>
    <fullName>Have_Note__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Have Note</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Have_Photo__c.field-meta.xml
<CustomField>
    <fullName>Have_Photo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Have Photo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Recommendation__c.field-meta.xml
<CustomField>
    <fullName>Recommendation__c</fullName>
    <label>Recommendation</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Target_Result__c.field-meta.xml
<CustomField>
    <fullName>Target_Result__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target Result</label>
    <referenceTo>Target_Result__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment_Target__c/Assessment_Target__c.object-meta.xml
<CustomObject>
    <label>Assessment Target</label>
    <nameField>
        <label>Assessment Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Doc_Link__c/Custom_Doc_Link__c.object-meta.xml
<CustomObject>
    <label>Custom Doc Link</label>
    <nameField>
        <label>Custom Doc Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Doc Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Doc_Link__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>Custom Doc Links</relationshipLabel>
    <relationshipName>Custom_Doc_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Doc_Link__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Custom Doc Links</relationshipLabel>
    <relationshipName>Custom_Doc_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_User__c/Site_User__c.object-meta.xml
<CustomObject>
    <label>Site User</label>
    <nameField>
        <label>Site User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_User__c/fields/Last_Token__c.field-meta.xml
<CustomField>
    <fullName>Last_Token__c</fullName>
    <label>Last Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_User__c/recordTypes/Inspector.recordType-meta.xml
<RecordType>
    <fullName>Inspector</fullName>
    <active>true</active>
    <label>Inspector</label>
</RecordType>

force-app/main/default/objects/Target_Result__c/Target_Result__c.object-meta.xml
<CustomObject>
    <label>Target Result</label>
    <nameField>
        <label>Target Results Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Target Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_Result__c/fields/Assessment_Target__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Target__c</fullName>
    <label>Assessment Target</label>
    <referenceTo>Assessment_Target__c</referenceTo>
    <relationshipLabel>Target Results</relationshipLabel>
    <relationshipName>Target_Results</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Target_Result__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Target Results</relationshipLabel>
    <relationshipName>Target_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InstructorControllerTest.cls
/**
 * Created by Razer on 7/12/2020.
 */

@IsTest
private class InstructorControllerTest {
    @TestSetup
    static void testSetup()
    {
        String questionnaireId = TestDataFactory.createQuestionnaire();
        String userId = TestDataFactory.createTestUser('Inspector');
        TestDataFactory.setAssessmentTarget(questionnaireId, userId, null);
    }
    @IsTest
    static void testBehavior()
    {
        Site_User__c testUser = [SELECT Id, Last_Token__c FROM Site_User__c WHERE RecordType.DeveloperName = 'Inspector'];

        InstructorController.getAssessmentTargets(testUser.Last_Token__c);

        Answer__c testAnswer =[SELECT Id, Have_Note__c, Have_Photo__c, Question__c, Answer__c, Target_Result__r.Questionnaire__c,
                Target_Result__r.Assessment_Target__c, Target_Result__c, Question__r.Questionnaire__c,
                Recommendation__c, Question__r.Question__c FROM Answer__c LIMIT 1];

        InstructorController.Answer newAnswer = new InstructorController.Answer(testAnswer);
        InstructorController.AnswerFile newFile = new InstructorController.AnswerFile();
        newFile.base64body = 'testbody,testBody';
        newFile.fileName = 'testFle';
        newFile.image = true;

        InstructorController.setAnswer(JSON.serialize(new List<InstructorController.Answer>{newAnswer}), JSON.serialize(newFile), null);

        Custom_Doc_Link__c link = new Custom_Doc_Link__c(
                Answer__c = testAnswer.Id
        );

        insert link;

        newAnswer.haveNote = true;
        newAnswer.note = 'testNote';
        newAnswer.haveImage = true;
        newAnswer.imageString = 'test,test';

        InstructorController.changeAnswer(JSON.serialize(newAnswer));

        InstructorController.getAnswerImage(testAnswer.Id);

        Target_Result__c result = [SELECT Id FROM Target_Result__c lIMIT 1];

        Map<String, String> params = new Map<String, String>{
                'resultId' => result.Id,
                'token' => testUser.Last_Token__c
        };

        InstructorController.submitAssessment(params);

        Question__c testQuestion = [SELECT Id FROM Question__c WHERE Name = 'test1' LIMIT 1];

        InstructorController.findNotes(testQuestion.Id);

        params.put('questionOrder', '0');
        InstructorController.wipeFromAnswer(params);

        InstructorController.wipeTargetResult(params);
    }
}