force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Target_Result__c.field-meta.xml
<CustomField>
    <fullName>Target_Result__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target Result</label>
    <referenceTo>Target_Result__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment_Target__c/Assessment_Target__c.object-meta.xml
<CustomObject>
    <label>Assessment Target</label>
    <nameField>
        <label>Assessment Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_Result__c/Target_Result__c.object-meta.xml
<CustomObject>
    <label>Target Result</label>
    <nameField>
        <label>Target Results Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Target Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_Result__c/fields/Assessment_Target__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Target__c</fullName>
    <label>Assessment Target</label>
    <referenceTo>Assessment_Target__c</referenceTo>
    <relationshipLabel>Target Results</relationshipLabel>
    <relationshipName>Target_Results</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Target_Result__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Target Results</relationshipLabel>
    <relationshipName>Target_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TargetReportControllerTest.cls
/**
 * Created by Razer on 7/12/2020.
 */

@IsTest
private class TargetReportControllerTest {
    @TestSetup
    public static void setup()
    {
        String questionnaireId = TestDataFactory.createQuestionnaire();
        String userId = TestDataFactory.createTestUser('Inspector');
        TestDataFactory.setAssessmentTarget(questionnaireId, userId, null);
        TestDataFactory.insertCustomSettings();
    }

    @IsTest
    static void testBehavior()
    {
        Assessment_Target__c target = [SELECT Id FROM Assessment_Target__c LIMIT 1];
        Target_Result__c result = [SELECT Id FROM Target_Result__c LIMIT 1];
        List<Question__c> questions = [SELECT Id FROM Question__c];
        List<Answer__c> answers = new List<Answer__c>();

        for (Question__c question : questions)
        {
            Answer__c answer = new Answer__c(
                    Question__c = question.Id,
                    Target_Result__c = result.Id,
                    Answer__c = 'No'
            );
            answers.add(answer);
        }

        answers[0].Answer__c = 'Yes';
        insert answers;

        Questionnaire__c lib = [SELECT Id FROM Questionnaire__c LIMIT 1];
        Test.setCurrentPage(Page.TargetReport);
        ApexPages.currentPage().getParameters().put('targetId', target.Id);
        ApexPages.currentPage().getParameters().put('libId', lib.Id);

        TargetReportController controller = new TargetReportController();
    }
}