force-app/main/default/objects/Assessment_Target__c/Assessment_Target__c.object-meta.xml
<CustomObject>
    <label>Assessment Target</label>
    <nameField>
        <label>Assessment Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_Result__c/Target_Result__c.object-meta.xml
<CustomObject>
    <label>Target Result</label>
    <nameField>
        <label>Target Results Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Target Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_Result__c/fields/Assessment_Target__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Target__c</fullName>
    <label>Assessment Target</label>
    <referenceTo>Assessment_Target__c</referenceTo>
    <relationshipLabel>Target Results</relationshipLabel>
    <relationshipName>Target_Results</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Target_Result__c/fields/Is_Started__c.field-meta.xml
<CustomField>
    <fullName>Is_Started__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Started</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Target_Result__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Target Results</relationshipLabel>
    <relationshipName>Target_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AssessmentTargetHandler.cls
/**
 * Created by Artsiom.Klimanski on 12/17/2019.
 */

public with sharing class AssessmentTargetHandler
{
    public static void createQuestionnaires(List<Assessment_Target__c> targets)
    {
        List<Questionnaire__c> libs = [
                SELECT Id FROM Questionnaire__c
        ];
        List<Target_Result__c> results = new List<Target_Result__c>();

        for (Assessment_Target__c target : targets)
        {
            for (Questionnaire__c questionnaire : libs)
            {
                Target_Result__c result = new Target_Result__c(
                        Assessment_Target__c = target.Id,
                        Questionnaire__c = questionnaire.Id,
                        Is_Completed__c = false,
                        Is_Started__c = false,
                        Created_Date__c = Date.today()
                );

                results.add(result);
            }
        }

        if (!results.isEmpty())
        {
            insert results;
        }
    }

}