force-app/main/default/objects/Ex_Login_History__c/Ex_Login_History__c.object-meta.xml
<CustomObject>
    <label>Session History</label>
    <nameField>
        <displayFormat>Ex-SH-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ex_Login_History__c/fields/Session_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Session_Expiration__c</fullName>
    <label>Session Expiration</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ex_Login_History__c/fields/Source_IP__c.field-meta.xml
<CustomField>
    <fullName>Source_IP__c</fullName>
    <label>Source IP</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Ex_Template_Controller_Test.cls
@isTest
public class Ex_Template_Controller_Test
{
    @testSetup static void dataSetup() {
        DELETE [SELECT Id FROM Ex_Login_History__c];
        
        // Login History
        DateTime dt =  DateTime.now(); 
        Ex_Login_History__c login = new Ex_Login_History__c(Source_IP__c = '192.68.1.1', Session_Expiration__c = dt.addHours(1));
        insert login;
    }
    
    @isTest
    static void itShould()
    {
        PageReference pageRef = Page.Ex_PasswordHomePage;
        Test.setCurrentPage(pageRef);
        
        Ex_Template_Controller ctr = new Ex_Template_Controller();
        
        ctr.checkUserSession();
        ctr.redirectToHomePage();
        
        if(ctr.isSessionOut())
        {
            ctr.password = 'Excalibur123';
            ctr.submitPassword();
        }
    }
    
    @isTest
    static void passwordIncorrect()
    {
        PageReference pageRef = Page.Ex_PasswordHomePage;
        Test.setCurrentPage(pageRef);
        
        Ex_Template_Controller ctr = new Ex_Template_Controller();
        
        ctr.checkUserSession();
        ctr.redirectToHomePage();
        
        if(ctr.isSessionOut())
        {
            ctr.password = 'wrongPassword';
            ctr.submitPassword();
        }
    }
}