force-app/main/default/objects/Completed_Task__c/Completed_Task__c.object-meta.xml
<CustomObject>
    <label>Completed Task</label>
    <nameField>
        <label>Completed Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Completed Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Completed_Task__c/fields/Meeting_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Scheduled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Meeting Scheduled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Completed_Task__c/fields/Meeting_Time__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Time__c</fullName>
    <label>Meeting Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Completed_Task__c/fields/Questionnaire_Task__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Questionnaire Task</label>
    <referenceTo>Questionnaire_Task__c</referenceTo>
    <relationshipLabel>Completed Tasks</relationshipLabel>
    <relationshipName>Completed_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Completed_Task__c/fields/Target_Result__c.field-meta.xml
<CustomField>
    <fullName>Target_Result__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Target Result</label>
    <referenceTo>Target_Result__c</referenceTo>
    <relationshipLabel>Completed Tasks</relationshipLabel>
    <relationshipName>Completed_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/JSON_Data__c.field-meta.xml
<CustomField>
    <fullName>JSON_Data__c</fullName>
    <label>JSON Data</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Questionnaire_Task__c/Questionnaire_Task__c.object-meta.xml
<CustomObject>
    <label>Questionnaire Task</label>
    <nameField>
        <label>Questionnaire Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaire Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Target_Result__c/Target_Result__c.object-meta.xml
<CustomObject>
    <label>Target Result</label>
    <nameField>
        <label>Target Results Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Target Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/WebHooks.cls
/**
 * Created by Razer on 28.01.2020.
 */
@RestResource(urlMapping='/webhoks')
global with sharing class WebHooks {


    @HttpPost
    global static String doPost()
    {
        String requestBody = RestContext.request.requestBody.toString();
        CalendyInfo newInfo = (CalendyInfo)JSON.deserialize(requestBody, CalendyInfo.class);
        try {
            insert new Completed_Task__c(
                    Questionnaire_Task__c = newInfo.payload.tracking.salesforce_uuid.substringBefore('_'),
                    Target_Result__c = newInfo.payload.tracking.salesforce_uuid.substringAfter('_'),
                    Meeting_Scheduled__c = true,
                    Meeting_Time__c = newInfo.payload.event.start_time
            );

        } catch (Exception e)
        {
            System.debug(e);
        }
        insert new Log__c(JSON_Data__c = requestBody);
        return '';
    }

    public class CalendyInfo
    {
        public Payload payload;

    }

    public class Payload
    {
        public Event event;
        public Invitee invitee;
        public Tracking tracking;
    }

    public class Event
    {
        public String start_time;
    }

    public class Invitee
    {
        public String email;
    }

    public class Tracking
    {
        public String salesforce_uuid;
    }

}