force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Branch_Order__c.field-meta.xml
<CustomField>
    <fullName>Branch_Order__c</fullName>
    <label>Branch Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Branches</relationshipLabel>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BranchTriggerHandler.cls
/**
 * Created by Razer on 29.01.2020.
 */

public with sharing class BranchTriggerHandler {

    public static void handleOrders(List<Branch__c> newRecords)
    {
        Map<String, List<Branch__c>> libBranchMap = new Map<String, List<Branch__c>>();
        Set<String> branchIds = new Set<String>();

        for (Branch__c branch : newRecords)
        {
            if (libBranchMap.containsKey(branch.Questionnaire__c))
            {
                libBranchMap.get(branch.Questionnaire__c).add(branch);
            } else {
                libBranchMap.put(branch.Questionnaire__c, new List<Branch__c>{branch});
            }

            if (branch.Id != null)
            {
                branchIds.add(branch.Id);
            }
        }

        List<Questionnaire__c> libs = [
            SELECT Id, (SELECT Id, Branch_Order__c FROM Branches__r WHERE Id NOT IN : branchIds)
            FROM Questionnaire__c
            WHERE Id IN : libBranchMap.keySet()
        ];

        for (Questionnaire__c lib : libs)
        {
            Map<Decimal, Branch__c> orderBranchMap = new Map<Decimal, Branch__c>();
            for (Branch__c branch : libBranchMap.get(lib.Id))
            {
                if (orderBranchMap.containsKey(branch.Branch_Order__c))
                {
                    branch.addError('You trying to insert branches with repeating orders');
                } else {
                    orderBranchMap.put(branch.Branch_Order__c, branch);
                }
            }


            for (Branch__c branch : lib.Branches__r)
            {
                if (orderBranchMap.containsKey(branch.Branch_Order__c))
                {
                    orderBranchMap.get(branch.Branch_Order__c).addError('You already have this Branch Order inside current Questionnaire.');
                }
            }
        }

    }

}