force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Yes_Skip_To_Question__c.field-meta.xml
<CustomField>
    <fullName>Yes_Skip_To_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Yes - Skip To Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuestionTriggerHandler.cls
/**
 * Created by Razer on 29.01.2020.
 */

public with sharing class QuestionTriggerHandler {

    public static void handleOrders(List<Question__c> newRecords)
    {
        Map<String, List<Question__c>> branchQuestionMap = new Map<String, List<Question__c>>();
        Set<String> questionsIds = new Set<String>();

        for (Question__c question : newRecords)
        {
            if (branchQuestionMap.containsKey(question.Branch__c))
            {
                branchQuestionMap.get(question.Branch__c).add(question);
            } else {
                branchQuestionMap.put(question.Branch__c, new List<Question__c>{question});
            }

            if (question.Id != null)
            {
                questionsIds.add(question.Id);
            }
        }

        List<Branch__c> branches = [
                SELECT Id, (SELECT Id, Order__c FROM Questions__r WHERE Id NOT IN : questionsIds)
                FROM Branch__c
                WHERE Id IN : branchQuestionMap.keySet()
        ];

        for (Branch__c branch : branches)
        {
            Map<Decimal, Question__c> orderQuestionMap = new Map<Decimal, Question__c>();
            for (Question__c question : branchQuestionMap.get(branch.Id))
            {
                if (orderQuestionMap.containsKey(question.Order__c))
                {
                    question.addError('You trying to insert questions with repeating orders');
                } else {
                    orderQuestionMap.put(question.Order__c, question);
                }
            }


            for (Question__c question : branch.Questions__r)
            {
                if (orderQuestionMap.containsKey(question.Order__c))
                {
                    orderQuestionMap.get(question.Order__c).addError('You already have this Question Order inside current Branch.');
                }
            }
        }
    }

}