force-app/main/default/objects/Site_User__c/Site_User__c.object-meta.xml
<CustomObject>
    <label>Site User</label>
    <nameField>
        <label>Site User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_User__c/fields/Last_Token__c.field-meta.xml
<CustomField>
    <fullName>Last_Token__c</fullName>
    <label>Last Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_User__c/recordTypes/Inspector.recordType-meta.xml
<RecordType>
    <fullName>Inspector</fullName>
    <active>true</active>
    <label>Inspector</label>
</RecordType>

force-app/main/default/objects/Site_User__c/recordTypes/User.recordType-meta.xml
<RecordType>
    <fullName>User</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/classes/UserControllerTest.cls
/**
 * Created by Razer on 7/13/2020.
 */

@IsTest
public class UserControllerTest
{
    @TestSetup
    static void testSetup()
    {
        String questionnaireId = TestDataFactory.createQuestionnaire();
        String instructorId = TestDataFactory.createTestUser('Inspector');
        String userId = TestDataFactory.createTestUser('User');
        TestDataFactory.insertCustomSettings();
        TestDataFactory.insertQA();
        TestDataFactory.setAssessmentTarget(questionnaireId, instructorId, userId);
    }

    @IsTest
    static void testBehaviour()
    {
        Site_User__c testUser = [SELECT Id, Last_Token__c FROM Site_User__c WHERE RecordType.DeveloperName = 'User' LIMIT 1];

        UserController.getTargetResults(testUser.Last_Token__c);
        UserController.getQuestions();

        List<UserController.TargetTask> testTasks = (List<UserController.TargetTask>)UserController.getTasksInfo(testUser.Last_Token__c);

        UserController.uploadTaskPhoto(JSON.serialize(testTasks[0].tasks[0]));

        testTasks[0].tasks[0].currentPhotoString = 'test,test';
        
        UserController.uploadTaskPhoto(JSON.serialize(testTasks[0].tasks[0]));

        System.debug(testTasks);

    }
}